# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn and Angular CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: yarn --version
    - run: yarn install
    - run: ./node_modules/.bin/ng --version
    - run: ./node_modules/.bin/ng lint
    - run: ./node_modules/.bin/ng build --configuration production
    - name: Get Current Time
      uses: gerred/current-time@v1.0.0
      id: current-time
    - name: Commit to GitHub Pages Repo
      uses: zwaldowski/git-commit-action@v1
      with:
        working_directory: ./dist/personal-website
        commit_message: Automated Commit by GitHub Actions (${{ steps.current-time.outputs.time }})
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITPAGE_TOKEN }}
        force: true
        repository: h36yang/h36yang.github.io
        directory: ./dist/personal-website
